remove non-existing team @riege/connect
riege/code-quality pull request #42
Opened 2023-05-19 12:21 UTC by mskopp

2023-05-19 12:26 UTC, QLwork approved these changes
LGTM, although we should probably use operations instead of plops in the future.

2023-05-20 00:02 UTC, wiebeck requested changes
Let's get all the teams straight.

2023-05-20 00:02 UTC, wiebeck commented on .github/CODEOWNERS
> +* @riege/core @riege/plops
As @QLwork said, let's also use team "Operations":
```suggestion
* @riege/core @riege/operations
```

2023-05-22 16:57 UTC, wiebeck approved these changes

2023-05-22 18:29 UTC, merged